ARG DEBIAN_VERSION
FROM docker.io/nqminhuit/debian-base:$DEBIAN_VERSION
ARG VERSION
RUN git clone --depth=1 -b $VERSION https://github.com/alacritty/alacritty.git
WORKDIR /alacritty
RUN cargo build --release --quiet
RUN ls -lah target/release/alacritty
RUN ls -lah extra

FROM scratch
COPY --from=0 /alacritty/target/release/alacritty /
COPY --from=0 /alacritty/extra /
COPY ./alacritty/Alacritty.desktop /Alacritty.desktop
