FROM localhost/emacs-base:latest
ARG INSTALL_PATH
RUN mkdir -p $INSTALL_PATH && \
    ./autogen.sh && \
    CFLAGS="-O3" \
    ./configure \
        --with-pgtk \
        --with-native-compilation=aot \
        --with-tree-sitter \
        --with-cairo \
        --with-rsvg \
        --with-sqlite3 \
        --with-webp \
        --with-mailutils \
        --without-compress-install \
    --prefix=$INSTALL_PATH && \
    make -j$(nproc) && \
    make install

FROM scratch
ARG INSTALL_PATH
COPY --from=0 $INSTALL_PATH/ /
