ARG DEBIAN_VERSION
FROM docker.io/nqminhuit/debian-base:$DEBIAN_VERSION
ARG VERSION
RUN git clone --depth 1 -b $VERSION https://github.com/tmux/tmux.git
WORKDIR /tmux
RUN ./autogen.sh && bash configure && make;
