ARG DEBIAN_VERSION
FROM docker.io/nqminhuit/debian-base:$DEBIAN_VERSION
ARG INSTALL_PATH
ARG VERSION
ARG TREE_SITTER_VERSION
ENV DEBIAN_FRONTEND=noninteractive

RUN git clone --depth 1 --branch $TREE_SITTER_VERSION https://github.com/tree-sitter/tree-sitter.git
RUN git clone --depth 1 --branch emacs-$VERSION https://github.com/emacs-mirror/emacs.git

WORKDIR /tree-sitter
RUN make -j 16 && make install
ENV LD_LIBRARY_PATH=/usr/local/lib/

WORKDIR /emacs
COPY emacs/emacs.desktop etc/emacs.desktop
COPY emacs/emacs.png etc/images/icons/hicolor/16x16/apps/emacs.png
COPY emacs/emacs.png etc/images/icons/hicolor/24x24/apps/emacs.png
COPY emacs/emacs.png etc/images/icons/hicolor/32x32/apps/emacs.png
COPY emacs/emacs.png etc/images/icons/hicolor/48x48/apps/emacs.png
COPY emacs/emacs.png etc/images/icons/hicolor/128x128/apps/emacs.png
COPY emacs/emacs.svg etc/images/icons/hicolor/scalable/apps/emacs.svg
COPY emacs/emacs.ico etc/images/icons/hicolor/scalable/apps/emacs.ico
RUN mkdir -p $INSTALL_PATH
ENV CC="gcc-11"
RUN ./autogen.sh && ./configure \
    --with-tree-sitter \
    --with-x-toolkit=gtk3 \
    --without-compress-install \
    --with-mailutils \
    --with-rsvg \
    --with-x11 \
    --prefix=$INSTALL_PATH
RUN make -j 16 && make install

# WORKDIR /
# RUN rm -rf emacs-$VERSION.tar.gz
# RUN rm -rf tree-sitter
# RUN rm -rf emacs-emacs-$VERSION
