FROM localhost/emacs-base:latest
ARG INSTALL_PATH
RUN mkdir -p $INSTALL_PATH && \
    ./autogen.sh && \
    CFLAGS="-O3" \
    ./configure \
        --with-tree-sitter \
        --with-x-toolkit=gtk3 \
        --without-compress-install \
        --with-mailutils \
        --with-rsvg \
        --with-cairo \
        --prefix=$INSTALL_PATH && \
    make -j$(nproc) && make install

FROM scratch
ARG INSTALL_PATH
COPY --from=0 $INSTALL_PATH/ /
