FROM localhost/emacs-base:latest
ARG INSTALL_PATH
RUN mkdir -p $INSTALL_PATH
RUN ./autogen.sh
RUN CFLAGS="-O3" ./configure \
    --without-compress-install \
    --with-tree-sitter \
    --with-cairo \
    --with-native-compilation=aot \
    --with-rsvg \
    --with-pgtk \
    --prefix=$INSTALL_PATH
RUN make -j$(nproc)
RUN make install

FROM scratch
ARG INSTALL_PATH
COPY --from=0 $INSTALL_PATH/ /
