ARG VERSION
FROM docker.io/ubuntu:$VERSION

RUN apt-get update && apt-get install -y curl git-core gnupg locales wget \
    build-essential libncurses5-dev libncursesw5-dev librsvg2-dev \
    automake libevent-dev ncurses-dev bison cmake libxml2-dev \
    texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev \
    nasm libx264-dev libxext-dev libxfixes-dev zlib1g-dev libwebkit2gtk-4.1-dev \
    libgccjit0 libgccjit-11-dev gcc-11 g++-11 libgnutls28-dev \
    libgtk-3-dev libncurses-dev autoconf pkg-config libfreetype6-dev \
    libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3 \
    libcairo2-dev libjansson-dev libtree-sitter-dev libwebp-dev mailutils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y;
ENV PATH=/root/.cargo/bin:"$PATH"
RUN rustup override set stable
RUN rustup update stable

RUN apt-get autoclean && apt-get autoremove
RUN git config --global advice.detachedHead false
