name: fd-find-container-build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'fd-find version'
        required: true
        default: v10.4.2
      debian_version:
        description: 'Debian version'
        required: true
        default: 13

jobs:
  build:
    uses: ./.github/workflows/build-and-push-container.yml
    with:
      name: fd
      version: ${{ inputs.version }}
      debian_version: ${{ inputs.debian_version }}
    secrets:
      DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_IO_TOKEN: ${{ secrets.DOCKER_IO_TOKEN }}
