name: fd-find-binary

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'fd version'
        required: true
        default: v10.4.2
      ubuntu-version:
        description: 'ubuntu version'
        required: true
        default: 26.04

jobs:
  build:
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          repository: sharkdp/fd
          ref: ${{inputs.version}}
      - name: compile fd
        run: cargo build --release --quiet
      - run: ./target/release/fd --version > $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v7
        with:
          name: fd
          path: target/release/fd
          archive: false
          if-no-files-found: error
