name: mpv

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'mpv version'
        required: true
        default: v0.39.0
      debian_version:
        description: 'Debian version'
        required: true
        default: 12

env:
  REGISTRY: docker.io
  NAME: mpv

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout mpv repository
        uses: actions/checkout@v4
        with:
          repository: mpv-player/mpv
          ref: ${{inputs.version}}
          token: ${{ secrets.PUBLIC_PAT }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavfilter-dev libplacebo-dev libass-dev ccache g++-mingw-w64 gcc-multilib meson nasm ninja-build pkg-config
        shell: bash

      - name: Build with meson
        id: build
        run: |
          meson setup build
          meson compile -C build
          # meson install -C build
          ls -lah
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: mpv
          path: build

      # - name: Build ${{env.NAME}} image
      #   run: podman build --build-arg DEBIAN_VERSION=${{inputs.debian_version}} --build-arg VERSION=${{inputs.version}} -f containers/Containerfile-${{env.NAME}} -t ${{env.NAME}}:${{inputs.version}}
      #   shell: bash

      # - name: Push ${{env.NAME}} image to ${{env.REGISTRY}}
      #   run: podman push --quiet --creds ${{secrets.DOCKER_IO_USERNAME}}:${{secrets.DOCKER_IO_TOKEN}} ${{env.NAME}}:${{inputs.version}} docker://docker.io/nqminhuit/${{env.NAME}}:${{inputs.version}}
      #   shell: bash
