name: Build Podman from source

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'podman version'
        required: true
        default: v4.9.5
      netavark_version:
        description: 'netavark version'
        required: true
        default: v1.12.2
      ubuntu-version:
        description: 'ubuntu version'
        required: true
        default: 22.04

jobs:
  compile_podman:
    name: Build podman from source
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: >-
        sudo apt-get install -y make curl
        btrfs-progs
        iptables
        libassuan-dev
        libbtrfs-dev
        libc6-dev
        libdevmapper-dev
        libglib2.0-dev
        libgpgme-dev
        libgpg-error-dev
        libprotobuf-dev
        libprotobuf-c-dev
        libseccomp-dev
        libselinux1-dev
        libsystemd-dev
        pkg-config
        uidmap
        slirp4netns
        catatonit
        fuse-overlayfs
        libapparmor-dev
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: "**/*.sum"
    - name: make executable
      run: |
        chmod +x ./tools/build_podman_dependencies.sh
        chmod +x ./tools/build_podman.sh
    - name: compile podman dependencies
      run: ./tools/build_podman_dependencies.sh
      shell: bash
    - name: install podman
      run: ./tools/build_podman.sh ${{inputs.version}}
      shell: bash
    - run: podman version > $GITHUB_STEP_SUMMARY
    - name: Upload podman
      uses: actions/upload-artifact@v4
      with:
        name: podman
        path: $HOME/tools/podman

  compile_netavark:
    name: Build netavark from source
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - name: Checkout netavark repository
      uses: actions/checkout@v4
      with:
        repository: containers/netavark
        ref: ${{inputs.netavark_version}}
        token: ${{ secrets.PUBLIC_PAT }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: netavark
        path: bin
