name: Build Podman from source

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'podman version'
        required: true
        default: v4.9.5

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: make executable
      run: chmod +x ./tools/build_podman.sh

    - name: install podman
      run: ./tools/build_podman.sh ${{inputs.version}}
      shell: bash

    - run: podman version > $GITHUB_STEP_SUMMARY

    - name: Upload podman
      uses: actions/upload-artifact@v4
      with:
        name: podman
        path: /usr/bin/podman
