name: Build Podman from source

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'podman version'
        required: true
        default: v4.9.5
      netavark_version:
        description: 'netavark version'
        required: true
        default: v1.12.2
      ubuntu-version:
        description: 'ubuntu version'
        required: true
        default: 22.04

jobs:
  compile_conmon:
    name: Compile conmon
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: containers/conmon
        token: ${{ secrets.PUBLIC_PAT }}
    - run: go version
    - name: compile conmon
      run: GOCACHE=$HOME/.go; make; sudo make podman
    - name: Upload conmon
      uses: actions/upload-artifact@v4
      with:
        name: conmon
        path: /usr/bin/conmon

  compile_runc:
    name: Compile runc
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: opencontainers/runc
        token: ${{ secrets.PUBLIC_PAT }}
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make libseccomp-dev
    - run: go version
    - name: compile runc
      run: make BUILDTAGS="selinux seccomp"; sudo cp runc /usr/bin/runc
    - name: Upload conmon
      uses: actions/upload-artifact@v4
      with:
        name: runc
        path: /usr/bin/runc

  compile_podman:
    name: Compile podman from source
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: containers/podman
        token: ${{ secrets.PUBLIC_PAT }}
        ref: ${{inputs.version}}
    - name: install dependencies
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y make curl
        btrfs-progs
        iptables
        libassuan-dev
        libbtrfs-dev
        libc6-dev
        libdevmapper-dev
        libglib2.0-dev
        libgpgme-dev
        libgpg-error-dev
        libprotobuf-dev
        libprotobuf-c-dev
        libseccomp-dev
        libselinux1-dev
        libsystemd-dev
        pkg-config
        uidmap
        slirp4netns
        catatonit
        fuse-overlayfs
        libapparmor-dev
    - run: go version
    - name: compile podman dependencies
      run: make BUILDTAGS="selinux seccomp" PREFIX=/usr; sudo make install PREFIX=/usr
      shell: bash
    - run: podman version > $GITHUB_STEP_SUMMARY
    - name: Upload podman
      uses: actions/upload-artifact@v4
      with:
        name: podman
        path: .

  compile_netavark:
    name: Compile netavark from source
    runs-on: ubuntu-${{inputs.ubuntu-version}}
    steps:
    - name: Checkout netavark repository
      uses: actions/checkout@v4
      with:
        repository: containers/netavark
        ref: ${{inputs.netavark_version}}
        token: ${{ secrets.PUBLIC_PAT }}
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make protobuf-compiler
    - run: rustc --version
    - run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: netavark
        path: bin
