name: Build Podman from source

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: make executable
      run: chmod +x ./tools/build_podman.sh
    - name: install podman
      run: ./tools/build_podman.sh
      shell: bash
    - run: podman version
