name: tmux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tmux version'
        required: true
        default: 3.7c
        type: choice
        options:
          - 3.5a
          - 3.6a
          - 3.6b
          - 3.7c
      debian_version:
        description: 'Debian version'
        required: true
        default: 13

jobs:
  build:
    uses: ./.github/workflows/build-and-push-container.yml
    with:
      name: tmux
      version: ${{ inputs.version }}
      debian_version: ${{ inputs.debian_version }}
    secrets:
      DOCKER_IO_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_IO_TOKEN: ${{ secrets.DOCKER_IO_TOKEN }}
